theme: jekyll-theme-dinky
position: fixed

title: Canonical Correlation Analysis, an example in R
description: |
   <a href="https://vguillemot.github.io/2Tables/#id1">Description</a> <br>
   <a href="https://vguillemot.github.io/2Tables/#id2">CCA</a> <br>
   <a href="https://vguillemot.github.io/2Tables/#id3">Wine Data-set</a> <br>
   <a href="https://vguillemot.github.io/2Tables/#id4">Latent Variables</a> <br>
   <a href="https://vguillemot.github.io/2Tables/#id5">Loadings</a> <br>
   <a href="https://vguillemot.github.io/2Tables/#id6">Correlation Circles</a> <br>
  


author :
  name : Vincent Guillemot
  github : vguillemot
