theme: jekyll-theme-dinky
position: fixed

title: Canonical Correlation Analysis, an example in R
description: https://vguillemot.github.io/2Tables/#id2

author :
  name : Vincent Guillemot
  github : vguillemot
