theme: jekyll-theme-dinky

position: fixed

title: Canonical Correlation Analysis
description: |
   <a href="https://vguillemot.github.io/2Tables/01_description.html">Description</a> <br>
   <a href="https://vguillemot.github.io/2Tables/02_CCAoverview.html">CCA</a> <br>
   <a href="https://vguillemot.github.io/2Tables/03_winedataset.html">Wine Data-set</a> <br>
   <a href="https://vguillemot.github.io/2Tables/04_LVs.html">Latent Variables</a> <br>
   <a href="https://vguillemot.github.io/2Tables/05_loadings.html">Loadings</a> <br>
   <a href="https://vguillemot.github.io/2Tables/06_cc.html">Correlation Circles</a> <br>

markdown: kramdown
use_math: true

author :
  name : Vincent Guillemot
  github : vguillemot

sections:
  - CCA
  - Wine
  - LV
  - Loadings
  - Corr. Circles
