theme: jekyll-theme-dinky
position: fixed

title: Canonical Correlation Analysis, an example in R
description: <a href="https://vguillemot.github.io/2Tables/#id2">link text</a>


author :
  name : Vincent Guillemot
  github : vguillemot
