theme: jekyll-theme-dinky
position: fixed

title: <a href="https://vguillemot.github.io/2Tables">Canonical Correlation Analysis, an example in R</a>
description: |
   <a href="https://vguillemot.github.io/2Tables/01_description.html">Description</a> <br>
   <a href="https://vguillemot.github.io/2Tables/02_CCAoverview.html">CCA</a> <br>
   <a href="https://vguillemot.github.io/2Tables/03_winedataset.html">Wine Data-set</a> <br>
   <a href="https://vguillemot.github.io/2Tables/04_LVs.html">Latent Variables</a> <br>
   <a href="https://vguillemot.github.io/2Tables/#id5">Loadings</a> <br>
   <a href="https://vguillemot.github.io/2Tables/#id6">Correlation Circles</a> <br>

author :
  name : Vincent Guillemot
  github : vguillemot
