theme: jekyll-theme-modernist
position:fixed

title: Canonical Correlation Analysis, an example in R
description: We present an example of a Canonical Correlation analysis of a small example data-set. The data-set contains two blocks of variables describing various characteristics of severals wines (white, rosé or red). 

author :
  name : Vincent Guillemot
  github : vguillemot
